# Structure de la présentation

## But de la recherche

La question: Est-ce que les changements dans la relation diplomatique entre les États-Unis affecte leur relations économiques?


Selon gordon mace: Les raisons de choisire un sujet:
- L'intéret porté au sujet
    Check
- L'ampleur et la qualité du corpus
    Corpus de texte immense mais éventail théorique pas si vaste. Accès à la littérature chinoise possible mais un peut plus compliqué. Biais car une grande parti des sources ne viennent pas de la chine.
- Pertinence sociale et  politique du sujet
    Très pertinent puisque d'actualité et les impacts possible sur nos sociétés sont mulitples 
- Instruments de recherche disponibles

    
# Deuxième étape de Gordon Mace

## Identifier le problème général
Identifier les principales dimensions du thème à étudier qui, de facon générale, est trop large pour faire l'objet d'une recherche
## Identifier le problème spécifique 
Exercice de lecture critique de la littérature produite sur la dimension ou le thème particulier 

## Ce qui sera traité dans la deuxième étape:
    - La raison d'être de la formulation du problème
    - La nature de problème de recherche 
    - Étapes de la formulation du problème, reconnaissance du problème générale de recherche
    - formulation du problème spécifique

## Pourquoi formuler un problème?

Okokokokok.

Formulation:

Les États-Unis émergent de la guerre froide comme victorieux. On parle d'hégémonie, on parle de fin de l'histoire, on peut finalement vivre heureux dans l'abondance.

Les États-Unis ont de l'argent, étendent leur influence à travers la planète, financent des coups d'états à gauche à droite, c'est le party.

Mais dans l'ombre, la chine qui jadis sommeillait, maintenant grandit, propulsé par les rentrés de capitaux étrangers, notament en provenance des états-unis.

Fameuse phrase de Deng Xiaoping: Bide your time. 

Maintenant, après plusieurs échecs de son modèle gouvernance économique, les états-unis sont face à un competiteur, non libéralisé, avec presque autant de capacité, qui fait la promotion d'un système antithétique aux états-unis.

Les théories libérales qui prédisaient la libéralisation de la Chine, que la Chine allait participer au Système internationales ont eu tort de croire que ce serait aussi facile.

De l'autre côté les réalistes qui prédisaient un conflit entre les deux puissance ont aussi tort. 

Les tensions sont élevés. Qu'est-ce qui va se passer entre ces deux grandes puissances? Qui peut répondre à cette question?

Gordon Mace explique ce phénomène comme une situation d'arrivée insatisfaisante.

Ceci est un problème de recherche.

## Formuler un problème de recherche?

Faire état des travaux antérieurs concernant l'objet d'étude 

- Quels dimensions du sujet ont été étudiés précédemment
- Sous quels angles?
- Quelle ampleur?
- Quels ancrages théoriques ont été utilisés dans les analyses?
- Quels sont les forces et les faiblesses?

# Identifier les lacunes analytiques

Les lacunes analytiques:
Les réalismes ne peuvent pas expliquer pourquoi la Chine s'est joint au WTO. Pourquoi

Savoir qui est mon audience. Qui va être dans la salle? Quel style? Informational? Technical?

Qu'est-ce qu'ils veulent?

Comment je peux conter l'histoire que je veux communiquer?
Structure d'une histoire.

And - Background
But - Problem (Emotional?)
Therefore - Solution to the problem

Personne va se rappeler ce que j'ai dit mais ils faut qu'ils se rappellent qu'il y a un gros problème




# explication du projet en 30 secondes
# AND
En ce moment si on se fie aux médias, on pourrait croire que les États-Unis et la Chine sont présentement en guerre froide:

Les articles de nouvelles qui parlent de la nouvelle guerre froide pullulent sur le web. Si nous sommes maintenant en guerre froide, qu'en est-il des relations économiques? Durant la guerre froide, les liens économiques entre les États-Unis et l'union soviétique étaient très faible mais aujourd'hui les États-Unis sont interdependent économiquement, peut-on vraiment parler de guerre froide?

Ma question est donc: Comment les changements diplomatiques entre la Chine et les États-Unis affectent-ils leurs relations économiques?

En premier on doit définir diplomatique.

La définition de Hans Morgenthau:
> La méthode d'établissement de la paix à travers les accomodements

Selon lui la diplomatie doit remplir 4 objectifs:
    1. Déterminer ses objectifs en fonction des pouvoirs actuellement et potentiellement disponible
    2. Déterminer les objectifs des autres états en fonction des pouvoirs actuellement et potentiellement disponible
    3. Déterminer la compatibilité de ses propres objectifs avec celui des autres états
    4. Employer les moyens nécessaires pour atteindre ses objectifs

Les États-Unis se sont retrouvé dans un état où ils n'avaient plus besoin de diplomatie. Leur suprématie était suffisante. Par contre, cette époque est révolu et le manque de diplomatie est devenu un problème.

## Deux plus grandes puissances
La Chine et les États sont les deux plus grandes puissances économiques et militaire sur la planète en ce moment. Pour vous donner un ordre d'idée j'ai ici quelques graphiques qui démontrent à quel point les deux pays se démarquent.

INCLURE GRAPHIQUE CHOC

## Accès au armes nuc + sommes faramineuses + participent aux organisations
Les deux pays ont accès aux armes nucléaires, les deux pays ont un budget militaire faramineux, investissent des sommes d'argent monstre chaque années à l'étranger, les deux pays participent à un pléthore d'organisations internationales conjointement. QUe ce soit ci ou ça ou ceci ou cela (INCLURE ORGANISATIONS INTERNATIONALES)

## Comment ils en sont arrivé là?
Les deux pays en sont justement arrivé à cette situation en colaborant. Pour dresser un portrait simple de la situation, Les États-Unis en faisant affaire avec la Chine ont pu bénéficier de l'accès à de la main d'oeuvre bon marché et la Chine a pu se trouver un client qui avait assez d'apétit pour acheter tout ce qu'elle avait à vendre.

## Interdépendance?
En commerçant ainsi, la Chine et les États-Unis ont développé leur interdépendance. C'est à dire qu'ils se sont volontairement mis dans une position où ils dépendent l'un de l'autre pour évoluer. À l'origine les États-Unis ne s'attendaient pas à ce que la Chine se développe autant et devienne une rivale, ils se sont donc lancer dans cette relation les yeux fermés.

## La chine savait ce qu'elle faisait
De son côté la Chine savait ce qu'elle faisait. Une fameuse citation de l'ancien chef du parti communiste était: Hide your strength, bide your time. Ils savaient qu'en ouvrant leur portes aux investissements étrangers, ils pourraient bénéficier d'un immense flux de capitaux qu'il pourraient utiliser pour faire fructifier leur économie.

## Plus grand exploit economique de tous les temps
La Chine, à partir de 1979 jusqu'en 2012 a accompli le plus grand exploit économique de tous les temps. A sorti 750000000 de personnes de la pauvreté et a su diversifier plusieurs de ses secteurs d'activité. La Chine, pour les États-Unis, ne représentait pas encore une menace puisqu'elle semblait se libéraliser, son économie ouverte, vulnérable aux aléats du libre marché. Mais en 2012 avec l'Arrivée au Pouvoir de Xi jinping, une tendance sembla se démarquer.

La Chine après plusieurs années à s'ouvrir, sembla maintenant sur le point de se refermer. Le pays qui bénéficia des prédicats économiques des américains semblait maintenant rejeter tous les notions libérales. Ceci changea la donne, il ne s'agissait plus de parler de democratic peace theory, la Chine rejetait maintenant complètement et ouvertement les notions de démocratie.

S'agissait-il de la fin d'une ère d'amabilité? C'est ici que nous en sommes. Après des décénies de coopération et de développements diplomatiques, la Chine et les États-Unis ne semblent plus bien s'entendre, dumoins si on se fie aux gouvernements et aux médias.

## L'élection de trump n'a pas aidé
L'élection de Trump n'a pas aidé parce qu'il a pu recadrer les relations sino-américaine comme une de compétition donc c'est devenu difficile pour les politiciens américains de parler de la Chine positivement sans se faire accuser de toute sorte de choses.

# Question de recherche
Comment expliquer la stabilité apparente des relations économiques entre la Chine et les États-Unis malgré la dégradation apparente de leur relation diplomatique?

Le réalisme parle de pouvoir relatif et de rationalisme. N'est-ce pas irrationel pour les États-Unis de continuer à faire affaire avec la Chine? Oui les États-Unis ont intérêt à poursuivre leur relation économique avec la Chine mais ce serait insoutenable à long terme. La Chine est en train de devenir une menace pour les États-Unis et les États-Unis ne peuvent pas se permettre de laisser la Chine devenir une menace.

Pour les institutionalistes qui voient le pouvoir de façon absolue, ce n'est pas incompréhensible que les deux pays continuent de commercer et de colaborer sur divers projets économiques. Cependant, les institutionalistes expliquent mal le fait que leur relation économique ne semble pas affecté par leurs tensions politiques.


Hypothèse?



